name: silver_heart
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  firebase_storage: ^10.2.17
  firebase_database: ^9.0.15
  sailor: ^0.7.1
  geolocator: ^8.2.1
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  carousel_slider: ^4.1.1
  equatable: ^2.0.3
  injectable: ^1.5.3
  shared_preferences: ^2.0.15
  dartz: ^0.10.1
  flushbar: ^1.10.4
  another_flushbar: ^1.10.29
  google_fonts: ^3.0.1
  meta: ^1.7.0
  google_sign_in: ^5.3.3
  pedantic: ^1.11.1
  path: ^1.8.1
  flutter_hooks: ^0.18.5
  page_indicator: ^0.4.1
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.1
  get_it: ^7.2.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.png
    - assets/gift.png
    - assets/google-login-icon.png
    - assets/pay-services.png
    - assets/graphics.png
    - assets/post.png
    - assets/shop-app.png
    - assets/shop-bag.png
    - assets/support-two.png
    - assets/support.png
    - assets/up-money.png
    - assets/work.png
    - assets/user.png
    - assets/edit.png

